import Head from 'next/head'
import { Layout, theme, Menu } from 'antd';
import React, { ReactNode, useState } from "react";
import styles from '../styles/Home.module.css'
import Navbar from './Navigation/Navbar';
import PageFooter from './footer'
import SideMenu from './Navigation/Sider';
import {
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    UploadOutlined,
    UserOutlined,
    VideoCameraOutlined,
} from '@ant-design/icons';

const { Content, Footer, Header, Sider } = Layout;

const PageLayout = ({ children, title }: {children: ReactNode, title:any}) => {
    const [collapsed, setCollapsed] = useState(false);
    const {
        token: { colorBgContainer },
      } = theme.useToken();
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout className={styles.main} hasSider>
                <SideMenu></SideMenu>
                <Layout className={styles.page}>
                    <Navbar title={title}></Navbar>
                    <Content className={styles.content}>
                        {children}
                    </Content>
                    {/* <PageFooter></PageFooter> */}
                </Layout>
            </Layout>
        </div>
    );
}

export default PageLayout;
